# This is a basic workflow to help you get started with Actions
name: Update channels by schedules

# Controls when the workflow will run
on:
  # push:  
  workflow_call:
  schedule:
    - cron: "18 9 */2 * *"
    
  workflow_dispatch: # Allows you to run the action manually for testing
  
permissions:
  contents: write # Required to push changes back to the repo
  # pages: write
  # id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: github
  cancel-in-progress: true
  
jobs:
  update-channels-and-commit:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Start the job
      - name: Start the job
        run: |
          echo Hello, world! 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: Show current time
        run: |
          echo "Current datetime: $(date)"
      - name: Download file via curl
        run: |
          curl -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o get_vnchannel.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/get_vnchannel.py  & 
          # curl -L -o phimbotvb.m3u ${{ secrets.URL_TVB }}  &  
          
          wait
          ls -lh

      - name: Download, get & convert links to M3U8 files
        run: |
          if [ -f get_vnchannel.py ]; then
            python get_vnchannel.py
            
            # python get_vnchannel.py vtv1_hd
            # python get_vnchannel.py vie_channel_htv2_hd
            # python get_vnchannel.py htv7_hd
            # python get_vnchannel.py htv9_hd
            # python get_vnchannel.py htv_the_thao
            # python get_vnchannel.py thvl1_hd
          fi
          wait
          
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     # Upload entire repository
      #     path: 'm3ufiles/'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v5        

      - name: Commit and push changes
        run: |
          git config --local user.name "thcoban [bot]"
          git add *.m3u8
          git commit -m "[no ci] Update .m3u8 files"
          git push
